services:
  postgres_db:
      image: postgres:latest
      container_name: postgres_for_test
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: MyPassword
        POSTGRES_DB: mydb
      volumes:
        - postgres_data:/data/postgres_db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  postgres_data:
    driver: local